import { Logger } from '@nestjs/common';
import { existsSync, readdirSync } from 'node:fs';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join, normalize, sep } from 'node:path';
import { StorageDriver } from './storage-driver';

// The single source of truth for where uploaded files are served from, shared with main.ts's
// static-mount call — defined once here so the two can never drift apart. An operator only ever
// sets LOCAL_STORAGE_PUBLIC_BASE_URL to a bare origin (no path); this is appended automatically.
export const LOCAL_STORAGE_URL_PREFIX = '/uploads';

export interface LocalStorageDiagnostics {
  directoryConfigured: boolean;
  publicBaseConfigured: boolean;
  directoryExists: boolean;
  salonsDirectoryExists: boolean;
  salonDirectoryCount: number | null;
}

/** Safe startup facts only: no credentials, filenames, salon IDs or URLs are logged. */
export function inspectLocalStorageConfig(): LocalStorageDiagnostics {
  const dir = process.env.LOCAL_STORAGE_DIR?.trim();
  const publicBase = process.env.LOCAL_STORAGE_PUBLIC_BASE_URL?.trim();
  const salonsDir = dir ? join(dir, 'salons') : null;
  let salonDirectoryCount: number | null = null;
  if (salonsDir && existsSync(salonsDir)) {
    try {
      salonDirectoryCount = readdirSync(salonsDir, {
        withFileTypes: true,
      }).filter((entry) => entry.isDirectory()).length;
    } catch {
      salonDirectoryCount = null;
    }
  }
  return {
    directoryConfigured: Boolean(dir),
    publicBaseConfigured: Boolean(publicBase),
    directoryExists: Boolean(dir && existsSync(dir)),
    salonsDirectoryExists: Boolean(salonsDir && existsSync(salonsDir)),
    salonDirectoryCount,
  };
}

interface LocalDiskDriverConfig {
  /** Filesystem directory bytes are written under — the Railway volume's mount path in production. */
  dir: string;
  /** The backend's externally reachable origin, e.g. "http://localhost:3000" — no path. */
  origin: string;
}

/**
 * The launch storage driver: writes owner-uploaded photos to a directory backed by a Railway
 * persistent Volume, served back out through the backend's own static file middleware (wired in
 * main.ts). No object-storage account, bucket, or credentials required — the tradeoff, accepted
 * deliberately for launch, is that this only works with exactly one backend instance attached to
 * exactly one volume; it does not survive a multi-instance/horizontally-scaled deployment the way
 * S3CompatibleStorageDriver would. Swapping to R2 later needs no Photo-model or frontend change —
 * see ObjectStorageService's selection order and StorageDriver's own doc comment.
 */
export class LocalDiskStorageDriver implements StorageDriver {
  private readonly logger = new Logger(LocalDiskStorageDriver.name);

  private constructor(private readonly config: LocalDiskDriverConfig) {}

  /** Both LOCAL_STORAGE_DIR and LOCAL_STORAGE_PUBLIC_BASE_URL present and non-empty, or null. */
  static fromEnv(): LocalDiskStorageDriver | null {
    const dir = process.env.LOCAL_STORAGE_DIR?.trim();
    const origin = process.env.LOCAL_STORAGE_PUBLIC_BASE_URL?.trim();
    if (!dir || !origin) return null;
    return new LocalDiskStorageDriver({
      dir,
      // Trailing slash normalised once here so callers can always join with a single '/', same
      // convention as S3CompatibleStorageDriver.
      origin: origin.replace(/\/+$/, ''),
    });
  }

  /**
   * `key` is always server-generated by SalonPhotosService (`salons/<uuid>/photos/<uuid>.<ext>`),
   * never taken from a client-supplied filename — but a directory write is exactly the place a
   * `..` segment turns into a real filesystem escape, so it is refused here too rather than
   * trusted transitively from the caller.
   */
  private resolvePath(key: string): string {
    const resolved = normalize(join(this.config.dir, key));
    const root = normalize(this.config.dir) + sep;
    if (!resolved.startsWith(root)) {
      throw new Error(
        `Refusing to write outside the storage directory: "${key}"`,
      );
    }
    return resolved;
  }

  // contentType is part of StorageDriver's shared signature but unused here: Express's static
  // middleware (main.ts) infers Content-Type from the file extension when serving it back, and
  // that extension is always derived from the sniffed type by extensionForMimeType — so the two
  // never disagree in practice. S3CompatibleStorageDriver has no such inference and sets it
  // explicitly on the object.
  async putPublicObject(
    key: string,
    body: Buffer,
    _contentType: string,
  ): Promise<string> {
    const path = this.resolvePath(key);
    await mkdir(dirname(path), { recursive: true });
    // A single writeFile, not a stream: multer's memoryStorage already holds the whole upload as
    // one in-memory Buffer (capped at SALON_PHOTO_UPLOAD.maxBytes, 5 MB) by the time it reaches
    // here, so a second streaming pass over the same bytes would add complexity without reducing
    // peak memory use.
    await writeFile(path, body);
    return `${this.config.origin}${LOCAL_STORAGE_URL_PREFIX}/${key}`;
  }

  async deleteObject(url: string): Promise<void> {
    const prefix = `${this.config.origin}${LOCAL_STORAGE_URL_PREFIX}/`;
    if (!url.startsWith(prefix)) return; // Not one of ours — e.g. an owner-linked URL.
    const key = url.slice(prefix.length);
    try {
      await rm(this.resolvePath(key), { force: true });
    } catch (err) {
      // Deletion is cleanup, not the operation the caller asked for — a failure here must never
      // surface as "could not remove your photo" when the database row is already gone.
      this.logger.warn(
        `Local disk delete failed for key "${key}" (photo row was already removed): ${err instanceof Error ? err.message : 'unknown error'}`,
      );
    }
  }
}
